name: nautica
services:
  postgis:
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_USER=nautica
      - POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
      # If want to expose these ports outside dev PC,
      # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg: